source("./R/launch.R")
source("./R/mod_assign_split.R")
#source("./R/mod_debarcoder.R")
source("./R/mod_debarcoder_2dye.R")
source("./R/mod_debarcoder_3dye.R")
source("./R/mod_exp_info_api.R")
source("./R/mod_fcb_select.R")
source("./R/mod_mode.R")
source("./R/mod_sample_tag.R")
source("./R/mod_setup.R")
source("./R/mod_upload.R")
source("./R/mod_well_assign.R")
source("./R/util_debarcoder.R")
source("./R/util_gate_trans.R")
source("./R/util_regression.R")
source("./R/mod_debarcoder_select.R")
# install.packages("quadprog")
# library(quadprog)